version: '2.1'
services:
  auth_db:
    container_name: auth_db
    image: library/postgres:12.6
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth
    volumes:
      - database:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
volumes:
  database:
    external: true