version: '2.1'
services:
  user_info_db:
    container_name: user_info_db
    image: library/postgres:12.6
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=user_info
      - DB_PORT=5434
    volumes:
      - user_info_database:/var/lib/postgresql/data:z
    ports:
      - 5434:5432
volumes:
  user_info_database:
    external: true